name: cameratraps-detector

channels:
  - conda-forge
  - pytorch

dependencies:
  - nomkl
  - python=3.8
  - Pillow=9.1.0
  - nb_conda_kernels
  - ipykernel
  - tqdm
  - jsonpickle
  - humanfriendly
  - numpy
  - matplotlib
  - opencv
  - requests

  # for running MegaDetector v4
  # - tensorflow>=2.0  

  # for running MegaDetector v5
  - pandas
  - seaborn>=0.11.0
  - PyYAML>=5.3.1
  # - pytorch::pytorch=1.10.1
  # - pytorch::torchvision=0.11.2
  # - conda-forge::cudatoolkit=11.3
  # - conda-forge::cudnn=8.1
