name: cameratraps-detector-explicit

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8.15
  - Pillow=9.1.0 
  - tqdm=4.65.0
  - jsonpickle=3.0.0
  - humanfriendly=10.0
  - numpy=1.24.3
  - matplotlib=3.7.1
  - opencv=4.5.5
  - requests=2.29.0

  # So we can run Jupyter in this environment
  - nb_conda_kernels=2.3.1
  - ipykernel=6.23.0
  
  # For running MegaDetector v4
  # - tensorflow>=2.0  

  # For running MegaDetector v5
  - pandas=2.0.1
  - seaborn=0.12.2
  - PyYAML=6.0
  - pytorch::pytorch=1.10.1
  - pytorch::torchvision=0.11.2
  - conda-forge::cudatoolkit=11.3
  - conda-forge::cudnn=8.1

